name: Workflow Run
on:
  workflow_run:
    workflows:
      - PR
    types:
      - completed
permissions:
  pull-requests: read
jobs:
  dump:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v7
        id: pr-id
        with:
          script: |
            const { data: pull_requests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: "${{ github.event.workflow_run.head_repository.owner.login }}",
              repo: context.repo.repo,
              commit_sha: "${{ github.event.workflow_run.head_sha }}",
            })
            return pull_requests[0]
      - run: echo "${{ steps.pr-id.outputs.result }}"
